# Flow: Create Team
name: 创建团队
category: team
description: 用户创建新团队的流程

trigger: click create-team-card
preconditions:
  - user.is_authenticated

steps:
  - step: 1
    page: home
    panel: publish-center
    component: create-team-card
    trigger: click
    result:
      action: open_modal
      target: create-team-modal

  - step: 2
    modal: create-team-modal
    component: team-form
    trigger: fill_form
    fields:
      - name: name
        required: true
        validation:
          min_length: 2
          max_length: 50
      - name: description
        required: false
        type: textarea
        validation:
          max_length: 500
      - name: visibility
        required: true
        type: select
        options:
          - value: public
            label: 公开
            description: 任何人可申请加入
          - value: private
            label: 私密
            description: 仅邀请可加入
        default: public
      - name: require_approval
        required: false
        type: checkbox
        label: 需要审批
        default: true
        condition: "visibility == 'public'"
      - name: max_members
        required: false
        type: number
        default: 10
        validation:
          min: 2
          max: 100

  - step: 3
    modal: create-team-modal
    component: submit-btn
    trigger: click
    api_call:
      method: POST
      endpoint: "/api/groups"
      body:
        name: "{form.name}"
        description: "{form.description}"
        visibility: "{form.visibility}"
        require_approval: "{form.require_approval}"
        max_members: "{form.max_members}"
      headers:
        X-User-Id: "{current_user.id}"
    loading_state: submit-btn

  - step: 4a
    condition: success
    result:
      - action: close_modal
        target: create-team-modal
      - action: navigate
        target: "/groups/{response.id}"
      - action: show_toast
        message: "团队创建成功"
        type: success

  - step: 4b
    condition: error
    error_codes:
      name_taken:
        action: show_field_error
        field: name
        message: "团队名称已被使用"
      default:
        action: show_toast
        message: "{error.message}"
        type: error
