"""initial_schema

Revision ID: 833ddc5dc597
Revises: 
Create Date: 2026-02-03 01:14:22.163639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833ddc5dc597'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('following_count')
        batch_op.drop_column('follower_count')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('participant_count')

    # ### end Alembic commands ###
