"""Models package - import all models so Base.metadata knows about them"""
from app.models.user import User
from app.models.resource import Resource
from app.models.category import Category
from app.models.post import Post
from app.models.rule import Rule
from app.models.group import Group
from app.models.interaction import Interaction
from app.models.comment import Comment
from app.models.rating import Rating
from app.models.member import Member
from app.models.user_user import UserUser
from app.models.post_resource import PostResource
from app.models.post_post import PostPost
from app.models.category_rule import CategoryRule
from app.models.category_post import CategoryPost
from app.models.category_group import CategoryGroup
from app.models.target_interaction import TargetInteraction
from app.models.category_category import CategoryCategory
from app.models.notification import Notification
